config/routes.rb
Rails.application.routes.draw do
  get 'users/Show'

  get 'users/new'

  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
     <%=link_to t("views.layouts.footer.rail_t"), "http://www.railstutorial.org/" %>
     <%=link_to t("views.layouts.footer.authors"), "http://www.michaelhartl.com/"%>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("views.layouts.footer.contact"),"#" %></li>
      <li><%= link_to t("views.layouts.footer.about"), about_path %></li>
      <li><%= link_to t("views.layouts.footer.new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to t("views.layouts.header.sample"), root_path , id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t("views.layouts.header.home"), root_path %></li>
            <li><%= link_to t("views.layouts.header.help"), help_path %></li>
            <li><%= link_to t("views.layouts.header.login"), signup_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1><%= t("views.static_pages.about.about")%></h1>
<p>
  <%= raw t("views.static_pages.about.about_t",
    rail_t: link_to(t("views.static_pages.rail_t"), "http://www.railstutorial.org/"),
    book: link_to(t("views.static_pages.about.book"), "http://www.railstutorial.org/book"),
    screens: link_to(t("views.static_pages.about.screens"), "http://screencasts.railstutorial.org"),
    ruby_on_rail: link_to(t("views.static_pages.about.ruby_on_rail"), "http://rubyonrails.org"))%>
    </p>

app/views/static_pages/help.html.erb
<h1><%= t(".help")%></h1>
<p><%= raw t("views.static_pages.help.help_t",
    help_p: link_to(t("views.static_pages.help.help_p"), "http://www.railstutorial.org/help"),
    rail_t: link_to(t("views.static_pages.rail_t"), "http://www.railstutorial.org/help"))%>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t"views.static_pages.home.welcome" %></h1>
  <h2><%= raw t("views.static_pages.home.home_t",
      rail_t: link_to(t("views.static_pages.rail_t"), "http://www.railstutorial.org/help")) %>
  </h2>
  <%= link_to t("views.static_pages.home.sign_up"), "#", class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
                                "http://rubyonrails.org/'=" %>
<%= image_tag("kitten.jpg", alt: "Kitten image") %>

app/views/users/new.html.erb
<h1><%= t("views.users.users") %></h1>